language: java

branches:
  only:
    - master

notifications:
  email:
    - prototypegamez@gmail.com

before_install:
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz -O android.tgz
  - tar -zxf android.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter platform-tools,android-16 --no-ui --force
